#!/usr/bin/env bash

function respond_with_icon() {
    local icon="$1"
    local text="$2"
    local tooltip="$3"
    local class="$4"
    if [[ -n "$icon" ]]; then
        text="<span font='Font Awesome 7 Free Solid'>$icon</span>$text"
    fi
    jq -cn --arg text "$text" --arg tooltip "$tooltip" --arg class "$class" '({text:$text, tooltip:$tooltip, class:$class} | with_entries(select(.value != null and .value != "")))'
}

function respond() {
    local text="$1"
    local tooltip="$2"
    local class="$3"

    respond_with_icon "" "$text" "$tooltip" "$class"
}

function get_temp_dir() {
    echo "${XDG_RUNTIME_DIR:-/tmp}"
}

function get_temp_file_named() {
  local name=$1
  echo "$(get_temp_dir)/${name}_$(id -u)"
}

function get_env_file() {
    local path=$1
    local filename=$(basename "$path")
    filename="${filename%.*}"
    echo "$(dirname "$path")/$filename.env"
}