#!/usr/bin/env bash

#!/usr/bin/env bash
# reload waybar with: pkill -SIGUSR2 waybar
# reload this module with: pkill -RTMIN+1 waybar
TOOLS=$(dirname "$(dirname "$(realpath "$0")")")/tools/functions
# shellcheck source=/home/pncolvr/.config/waybar/scripts/tools/functions
source "$TOOLS"

current=$(hyprctl activewindow -j | jq '.fullscreen' 2>/dev/null)
case $current in
    1) respond_with_icon "" "" "" "";;
    2|3) respond_with_icon "" "" "" "";;
esac

