#!/usr/bin/env bash
TOOLS=$(echo "${BASH_SOURCE[0]:-0}" | xargs realpath | xargs dirname)/tools/functions
# shellcheck source=/home/pncolvr/.config/waybar/scripts/tools/functions
source "$TOOLS"

value=$(date "+%Y-%m-%d") 
copy_to_clipboard_and_notify "$value"