#!/bin/bash
# reload waybar with: pkill -SIGUSR2 waybar
# reload this module with: pkill -RTMIN+3 waybar
TOOLS=$(dirname "${BASH_SOURCE[0]:-0}")/tools/functions
# shellcheck source=/home/pncolvr/.config/waybar/scripts/tools/functions
source "$TOOLS"

function toggle() {
    local muted=$(mic_is_muted)
    if [ "$muted" = true ]; then
        for SRC in $SOURCE_IDS; do
            wpctl set-mute "$SRC" 0
        done
    else
        for SRC in $SOURCE_IDS; do
            wpctl set-mute "$SRC" 1
        done
    fi
    pkill -RTMIN+3 waybar
}

function status() {
    local muted icon text tooltip class
    muted=$(mic_is_muted)
    if [ "$muted" = true ]; then
        icon=""
        class="disabled"
    else
        icon=""
    fi
    respond_with_icon "$icon" "$text" "$tooltip" "$class"

}

function mic_is_muted() {
    local muted=true
    for SRC in $SOURCE_IDS; do
        if ! wpctl get-volume "$SRC" | grep -q "MUTED"; then
            muted=false
            break
        fi
    done
    echo "$muted"
}

function get_sources() {
    while true
    do 
        local ids=$(wpctl status | awk '/Sources:/,/Sinks:/' | grep 'PRO X 2 LIGHTSPEED Mono' | awk '{print $3}' | tr -d '.')
        if [[ -n "$ids" ]]; then
            echo -n "$ids"
            return 
        else 
            sleep 0.1
        fi
    done
}

SOURCE_IDS=$(get_sources)
case $1 in 
    toggle) toggle;;
    status) status;;
esac
