#!/bin/bash
# reload waybar with: pkill -SIGUSR2 waybar
# reload this module with: pkill -RTMIN+3 waybar
TOOlS=$(echo "$0" | xargs realpath | xargs dirname)/tools/functions
# shellcheck source=/home/pncolvr/.config/waybar/scripts/tools/functions
source "$TOOlS"

function toggle() {
    ALL_MUTED=$(micIsMuted)
    if [ "$ALL_MUTED" = true ]; then
        for SRC in $SOURCE_IDS; do
            wpctl set-mute "$SRC" 0
        done
    else
        for SRC in $SOURCE_IDS; do
            wpctl set-mute "$SRC" 1
        done
    fi
    pkill -RTMIN+3 waybar
}

function status() {
    ALL_MUTED=$(micIsMuted)
    if [ "$ALL_MUTED" = true ]; then
        respondWithIcon ""
    else
        respondWithIcon ""
    fi
}

function micIsMuted() {
    ALL_MUTED=true
    for SRC in $SOURCE_IDS; do
        if ! wpctl get-volume "$SRC" | grep -q "MUTED"; then
            ALL_MUTED=false
            break
        fi
    done
    echo "$ALL_MUTED"
}

# if [ -z "$SOURCE_IDS" ]; then
#     respondWithIcon ""
#     exit 1
# fi

SOURCE_IDS=$(wpctl status | awk '/Sources:/,/Sinks:/' | grep 'PRO X 2 LIGHTSPEED Mono' | grep '^\s*│  \*' | awk '{print $3}' | tr -d '.')
case $1 in 
    toggle) toggle;;
    status) status;;
esac
