#!/bin/bash
# reload waybar with: pkill -SIGUSR2 waybar
# reload this module with: pkill -RTMIN+3 waybar
TOOLS=$(dirname "${BASH_SOURCE[0]:-0}")/tools/functions
# shellcheck source=/home/pncolvr/.config/waybar/scripts/tools/functions
source "$TOOLS"

function toggle() {
    ALL_MUTED=$(mic_is_muted)
    if [ "$ALL_MUTED" = true ]; then
        for SRC in $SOURCE_IDS; do
            wpctl set-mute "$SRC" 0
        done
    else
        for SRC in $SOURCE_IDS; do
            wpctl set-mute "$SRC" 1
        done
    fi
    pkill -RTMIN+3 waybar
}

function status() {
    ALL_MUTED=$(mic_is_muted)
    if [ "$ALL_MUTED" = true ]; then
        respond_with_icon ""
    else
        respond_with_icon ""
    fi
}

function mic_is_muted() {
    ALL_MUTED=true
    for SRC in $SOURCE_IDS; do
        if ! wpctl get-volume "$SRC" | grep -q "MUTED"; then
            ALL_MUTED=false
            break
        fi
    done
    echo "$ALL_MUTED"
}

function get_sources() {
    while true
    do 
        local ids=$(wpctl status | awk '/Sources:/,/Sinks:/' | grep 'PRO X 2 LIGHTSPEED Mono' | awk '{print $3}' | tr -d '.')
        if [[ -n "$ids" ]]; then
            echo -n "$ids"
            return 
        else 
            sleep 0.1
        fi
    done
}

SOURCE_IDS=$(get_sources)
case $1 in 
    toggle) toggle;;
    status) status;;
esac
