#!/usr/bin/env bash

if hyprctl activewindow | grep 'initialClass: mpv' > /dev/null 2>&1 && pgrep mpv > /dev/null 2>&1; then
    secs=$(playerctl -p mpv metadata --format '{{ (mpris:length - position) / 1000000 }}' | cut -d. -f1 )
    printf "%02d:%02d" $((secs/60)) $((secs%60))
fi