#!/usr/bin/env bash
# reload waybar with: pkill -SIGUSR2 waybar
# reload this module with: pkill -RTMIN+2 waybar
TOOLS=$(dirname "${BASH_SOURCE[0]:-0}")/tools/functions
# shellcheck source=/home/pncolvr/.config/waybar/scripts/tools/functions
source "$TOOLS"

function is_dnd_enabled() {
    [[ "$(swaync-client --get-dnd)" == "true" ]]
}

function status() {
    local icon text tooltip class
    if is_dnd_enabled; then
        icon=""
        tooltip="DND enabled"
    else
        icon=""
        tooltip="DND disabled"
    fi
    respond_with_icon "$icon" "$text" "$tooltip" "$class"
}

function toggle(){
    swaync-client --toggle-dnd
    pkill -RTMIN+2 waybar
    if is_dnd_enabled; then
        hyprctl notify -1 1000 "rgb(2E7D32)" "notifications disabled" > /dev/null 2>&1
    else 
        hyprctl notify -1 1000 "rgb(2E7D32)" "notifications enabled" > /dev/null 2>&1
    fi
}

function open_panel() {
    swaync-client --open-panel
}

case $1 in
    status) status ;;
    open-panel) open_panel;;
    toggle) toggle;;
esac