#!/usr/bin/env bash
# reload waybar with: pkill -SIGUSR2 waybar
# reload this module with: pkill -RTMIN+6 waybar
TOOLS=$(dirname "${BASH_SOURCE[0]:-0}")/tools/functions
# shellcheck source=/home/pncolvr/.config/waybar/scripts/tools/functions
source "$TOOLS"

FILE_TO_WATCH="$(get_temp_file_named screencast_status)"

if [[ ! -f "$FILE_TO_WATCH" ]]; then
    echo 0 > "$FILE_TO_WATCH"
fi

function check() {
    STATUS=$(cat $FILE_TO_WATCH)
    case $STATUS in
        1) on_screencast ;;
        *) on_no_screencast;;
    esac
}

function on_no_screencast() {
    respond
}

function on_screencast() {
    respond "" "screensharing"
}

check
