#!/usr/bin/env bash
# reload waybar with: pkill -SIGUSR2 waybar
# reload this module with: pkill -RTMIN+6 waybar
TOOLS=$(dirname "${BASH_SOURCE[0]:-0}")/tools/functions
# shellcheck source=/home/pncolvr/.config/waybar/scripts/tools/functions
source "$TOOLS"

FILE_TO_WATCH="$(get_temp_file_named screencast_status)"

if [[ ! -f "$FILE_TO_WATCH" ]]; then
    echo 0 > "$FILE_TO_WATCH"
fi

function check() {
    local status=$(cat $FILE_TO_WATCH)
    if [[ "$status" -eq 1 ]]; then
        respond "" "screensharing"
    fi
}

check
