#!/usr/bin/env bash
# reload waybar with: pkill -SIGUSR2 waybar
# reload this module with: pkill -RTMIN+2 waybar
TOOlS=$(echo "$0" | xargs realpath | xargs dirname)/tools/functions
# shellcheck source=/home/pncolvr/.config/waybar/scripts/tools/functions
. "$TOOlS"

function status() {
    if [[ "$(is-port-open bizdocssagedev.database.windows.net 1433)" == "Open" ]]; then
        respondWithIcon "" "" "sql reachable" "enabled"
    else
        respondWithIcon "" "" "sql not reachable"
    fi
}

case $1 in 
    "status") status;;
esac
