#!/usr/bin/env bash
# reload waybar with: pkill -SIGUSR2 waybar
# reload this module with: pkill -RTMIN+5 waybar
TOOLS=$(dirname "${BASH_SOURCE[0]:-0}")/tools/functions
# shellcheck source=/home/pncolvr/.config/waybar/scripts/tools/functions
source "$TOOLS"

source "$(get_env_file "${BASH_SOURCE[0]:-0}")"

STATUS_SCRIPT=$ZDOTDIR/scripts/status/manager.sh

function toggle() {
    "$STATUS_SCRIPT" --toggle
    reload
}

function check() {
    local status source icon text tooltip class
    status=$("$STATUS_SCRIPT" --check)
    source=$("$STATUS_SCRIPT" --source)
    class="$source"
    if [[ "$status" == "$WORKING_STATE_NAME" ]]; then
        icon=""
        tooltip="$WORKING_STATE_NAME"
    elif [[ "$status" == "$NOTWORKING_STATE_NAME" ]]; then
        icon=""
        tooltip="$NOTWORKING_STATE_NAME"
    else
        icon=""
        tooltip="unknown"
    fi
    respond_with_icon "$icon" "$text" "$tooltip" "$class"
}

function clear() {
    "$STATUS_SCRIPT" --clear
    reload
}

function reload() {
    pkill -RTMIN+5 waybar
}

case $1 in 
    toggle) toggle;;
    check) check;;
    clear) clear;;
esac
