#!/usr/bin/env bash

# generate new twitch token with twitch-cli token
# expand followed section on twitch
# and after on dev tools
# let elements = [... document.querySelectorAll('div[aria-label="Followed Channels"] div.side-nav-card__title > p[data-a-target]')]
# let names = elements.map(e => e.innerText.toLowerCase()).sort().join('\n')
# copy(names)
# then set TWITCH_USERS=(<result>) on the .env file

TOOLS=$(dirname "${BASH_SOURCE[0]:-0}")/tools/functions
# shellcheck source=/home/pncolvr/.config/waybar/scripts/tools/functions
source "$TOOLS"
source "$(get_env_file "${BASH_SOURCE[0]:-0}")"
ONLINE_FILE="$(get_temp_file_named twitch_online)"
TEMPLATE_JSON='{
    "prompt": "",
    "action": "output",
    "allowTyped": false,
    "allowMultipleSelection": false,
    "sort": false
}'

json=$(twitch-cli api get "streams?$(printf 'user_login=%s&' "${TWITCH_USERS[@]}")")
online_previous=""
if [[ -f "$ONLINE_FILE" ]]; then
    online_previous=$(<"$ONLINE_FILE")
fi

json_items=()
show=false
true > "$ONLINE_FILE"
for user in "${TWITCH_USERS[@]}"; do
    if echo "$json" | jq -e --arg u "$user" '.data[] | select(.user_login == $u)' >/dev/null 2>&1; then
        viewer_count=$(echo "$json" | jq -e --arg u "$user" '.data[] | select(.user_login == $u) | .viewer_count')
        online+=$(printf '<span %s>%s - %s</span>\r' 'foreground="#A970FF"' "$user" "$viewer_count")
        if ! echo -n "$online_previous" | grep -q "$user"; then
            notification+="$user\n"
        fi
        show=true
        json_items+=("$(jq -cn --arg title " $user" --arg result "https://www.twitch.tv/$user" '{title: $title, result: $result}')")
    else
        offline+=$(printf '<span %s>%s</span>\r' 'foreground="#FFFFFF"' "$user")
    fi
done

if [ ${#json_items[@]} -gt 0 ]; then
    items_json=$(printf '%s\n' "${json_items[@]}" | jq -s '.')
    final_json=$(jq -n --argjson items "$items_json" --argjson template "$TEMPLATE_JSON" '$template + {items: $items}')
    echo "$final_json" > "$ONLINE_FILE"
fi

tooltip+=$online
tooltip+=$offline
tooltip="${tooltip%$'\r'}"
notification="${notification%$'\r'}"
if [[ $show == true ]]; then
    if [ -n "$notification" ]; then 
        title="Online"
        notify-send --icon "$HOME"/Pictures/icons/twitch.png "$title" "$notification" --transient
    fi
    respond_with_icon "" "" "$tooltip" ""
else
    respond_with_icon "" "" "$tooltip" "disabled"
fi
