#!/usr/bin/env bash

TOOlS=$(echo "$0" | xargs realpath | xargs dirname)/tools/functions
# shellcheck source=/home/pncolvr/.config/waybar/scripts/tools/functions
source "$TOOlS"

TEMP_DIR="$(get_temp_dir)"

# generate new twitch token with twitch-cli token
# expand followed section on twitch
# and after on dev tools
# copy(
#   Array.from(document.querySelectorAll('a[data-test-selector="followed-channel"]'))
#     .map(a => a.href)
#     .join('\n')
# );

users=(
    anabitizi
    ashmonsterftw
    brodieongames
    cohhcarnage
    christitustech
    denims
    emiru
    enemycharlie
    harrie
    iamelkas
    joshstrifehayes
    krysttl
    leanbeefpatty
    linustech
    metatrongemini
    missmikkaa
    morgamix
    oxillery
    palmbee
    pernillamouritzen_
    pritkirin
    ricfazeres
    studytme
    sweet_anita
    taejen13
    tectone
    theprimeagen
    whatever
    yoon_froggy
    zackrawrr
)

json=$(twitch-cli api get "streams?$(printf 'user_login=%s&' "${users[@]}")")
online_file="$TEMP_DIR/twitch_online"
online_previous=""
if [[ -f "$online_file" ]]; then
    online_previous=$(<"$online_file")
fi

show=false
true > "$online_file"
for user in "${users[@]}"; do
    if echo "$json" | jq -e --arg u "$user" '.data[] | select(.user_login == $u)' >/dev/null 2>&1; then
        viewer_count=$(echo "$json" | jq -e --arg u "$user" '.data[] | select(.user_login == $u) | .viewer_count')
        online+=$(printf '<span %s>%s - %s</span>\r' 'foreground="#A970FF"' "$user" "$viewer_count")
        if ! echo -n "$online_previous" | grep -q "$user"; then
            notification+="$user\n"
        fi
        show=true
        printf '"%s"="%s"\n' "$user" "https://www.twitch.tv/$user" >> "$online_file"
    else
        offline+=$(printf '<span %s>%s</span>\r' 'foreground="#FFFFFF"' "$user")
    fi
done
tooltip+=$online
tooltip+=$offline
tooltip="${tooltip%$'\r'}"
notification="${notification%$'\r'}"
if [[ $show == true ]]; then
    if [ -n "$notification" ]; then 
        title="Online"
        notify-send --icon "$HOME"/Pictures/icons/twitch.png "$title" "$notification" --transient
    fi
    respond_with_icon "" "" "$tooltip" ""
else
    respond_with_icon "" "" "$tooltip" "disabled"
fi
