#!/usr/bin/env bash
# reload waybar with: pkill -SIGUSR2 waybar
# a sudo crontab was created with:
# 0 * * * * /usr/bin/yay -Sy --noconfirm >/dev/null 2>&1

TOOLS=$(echo "$0" | xargs realpath | xargs dirname)/tools/functions
# shellcheck source=/home/pncolvr/.config/waybar/scripts/tools/functions
source "$TOOLS"

MAX=80

mapfile -t updates < <(yay -Qu 2>/dev/null | sort)

count=${#updates[@]}

if [ "$count" -gt 0 ]; then
    priority_patterns=(
        "^linux"
        "nvidia"
        "^vivaldi"
        "^steam"
        "^firewall"
        "^visual-studio-code-bin"
        "^grub"
        "^hypr"
        "^streamcontroller"
        "^signal"
        "systemd"
        "^waybar"
    )
    priority_pattern=$(IFS='|'; echo "${priority_patterns[*]}")

    mapfile -t updates < <(
        { 
            printf '<span foreground="#ce7a27">%s</span>\r\n' "${updates[@]}" | grep -E "$priority_pattern";
            printf '<span>%s</span>\r\n' "${updates[@]}" | grep -vE "$priority_pattern";
        }
    )
    has_priority_update=$(printf '%s\n' "${updates[@]}" | grep -qE "$priority_pattern" && echo true || echo false)
    tooltip=$(printf '%s\n' "${updates[@]}" | head --lines $MAX )
    if [[ "$count" -gt "$MAX" ]]; then 
        tooltip+="… and $((count - MAX)) more"
    else 
        tooltip="${tooltip::-1}"
    fi

    class=$([[ $has_priority_update == true ]] && echo "priority" || echo "")
    respond_with_icon "" "" "$tooltip" "$class"
else 
    respond_with_icon "" "" "" "disabled"
fi