#!/usr/bin/env bash
# reload waybar with: pkill -SIGUSR2 waybar
# a sudo crontab was created with:
# 0 * * * * /usr/bin/yay -Sy --noconfirm >/dev/null 2>&1

# set the following variables on the .env file
# MAX=
# FOREGROUND_COLOUR=
# PRIORITY_PATTERNS=()

TOOLS=$(dirname "${BASH_SOURCE[0]:-0}")/tools/functions
# shellcheck source=/home/pncolvr/.config/waybar/scripts/tools/functions
source "$TOOLS"
source "$(get_env_file "${BASH_SOURCE[0]:-0}")"

mapfile -t updates < <(yay -Qu 2>/dev/null | sort)

count=${#updates[@]}
icon=""
text=
tooltip=
class=

if [ "$count" -gt 0 ]; then
    priority_pattern=$(IFS='|'; echo "${PRIORITY_PATTERNS[*]}")
    mapfile -t update_spans < <(
        { 
            printf '%s\n' "${updates[@]}" | grep -E "$priority_pattern" | xargs -I{} printf '<span foreground="%s">%s</span>\r\n' "$FOREGROUND_COLOUR" '{}';
            printf '%s\n' "${updates[@]}" | grep -vE "$priority_pattern" | xargs -I{} printf '<span>%s</span>\r\n' '{}';
        }
    )
    has_priority_update=$(printf '%s\n' "${updates[@]}" | grep -qE "$priority_pattern" && echo true || echo false)
    tooltip=$(printf '%s\n' "${update_spans[@]}" | head --lines $MAX )
    if [[ "$count" -gt "$MAX" ]]; then 
        tooltip+="… and $((count - MAX)) more"
    else 
        tooltip="${tooltip::-1}"
    fi

    class=$([[ $has_priority_update == true ]] && echo "priority" || echo "")
else 
    class=disabled
fi

respond_with_icon "$icon" "$text" "$tooltip" "$class"
