#!/usr/bin/env bash

# set the following variables on the .env file for the vm you want
# MACHINE_NAME=
# MACHINE_IP=
# MACHINE_PORT=

TOOLS=$(echo "$0" | xargs realpath | xargs dirname)/tools/functions
# shellcheck source=/home/pncolvr/.config/waybar/scripts/tools/functions
source "$TOOLS"
source "$(get_env_file "$0")"

# shellcheck source=/home/pncolvr/Projects/scripts/rofi/remotes/handle-virtual-machine.sh
source "$HOME"/Projects/scripts/rofi/remotes/handle-virtual-machine.sh


TEMP_DIR="$(get_temp_dir)"

FILE_TO_WATCH="$TEMP_DIR/${MACHINE_NAME}_status"

function recreate_file() {
    if [ ! -f "$FILE_TO_WATCH" ]; then
        touch "$FILE_TO_WATCH"
    fi
}

function check() {
    virshStatus=$(virsh -c qemu:///system list | grep "$MACHINE_NAME" | awk '{ print $3 }')
    if [[ "$virshStatus" == "running" ]]; then
        STATUS=$(cat $FILE_TO_WATCH)
        case $STATUS in 
            booting) respond "" "$MACHINE_NAME booting" "booting";;
            booted) respond "" "$MACHINE_NAME booted" "booted";;
            stopping) respond "" "$MACHINE_NAME stopping" "stopping";;
            error) respond "" "$MACHINE_NAME couldnt connect" "error";;
            *) respond "" "$MACHINE_NAME stopped" "stopped";;
        esac
    else
        status=$(cat "$FILE_TO_WATCH")
        if [[ ! "$status" == "stopped" ]]; then
            echo "stopped" >  "$FILE_TO_WATCH"
            respond "" "$MACHINE_NAME stopped" "stopped"
        fi
    fi
}

function monitor(){
    recreate_file
    check
    while true; do
        if inotifywait -q -t 15 -e modify,delete,move "$FILE_TO_WATCH" > /dev/null 2>&1; then
            recreate_file
            check
        else
            recreate_file
            check
        fi
    done
}

function toggle() {
    status=$(toggle_virtual_machine "$MACHINE_NAME")
    [[ $status == "starting" ]] && monitor_virtual_machine "$MACHINE_IP" "$MACHINE_PORT" "$MACHINE_NAME"
}

function focus() {
  address=$(hyprctl clients -j | \
   jq -r --arg title "$MACHINE_NAME" \
    '[.[] | select(.class=="xfreerdp" and .title==$title)] | .[0].address // ""')
   hyprctl dispatch focuswindow "address:$address"
}

case $1 in
    monitor) monitor;;
    toggle)  toggle;;
    focus)   focus;;
esac
